# Generated by Django 5.1.2 on 2024-10-31 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('num_ss', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
                ('imagen_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Coche', 'Coche'), ('Moto', 'Moto'), ('Camión', 'Camión')], max_length=10)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('fecha_fabricacion', models.DateField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zona_DRS_APP.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('coste', models.FloatField()),
                ('imagen_url', models.URLField()),
                ('mecanico', models.ManyToManyField(related_name='reparaciones', to='Zona_DRS_APP.mecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zona_DRS_APP.vehiculo')),
            ],
        ),
    ]
