# Generated by Django 5.1.2 on 2024-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('num_ss', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('marca', models.TextField()),
                ('modelo', models.TextField()),
                ('color', models.TextField()),
                ('fecha_fabricacion', models.DateField()),
                ('mecanicos', models.ManyToManyField(related_name='vehiculos', to='Zona_DRS_APP.mecanico')),
                ('propietarios', models.ManyToManyField(related_name='vehiculos', to='Zona_DRS_APP.propietario')),
            ],
        ),
    ]
