# Generated by Django 5.1.2 on 2024-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zona_DRS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='mecanicos',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='propietarios',
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
