# Generated by Django 5.1.2 on 2024-12-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zona_DRS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparacionVehiculos', to='Zona_DRS_APP.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Zona_DRS_APP.propietario'),
        ),
    ]
