# Generated by Django 5.1.2 on 2024-10-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Zona_DRS_APP', '0002_remove_vehiculo_mecanicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('num_ss', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('marca', models.TextField()),
                ('modelo', models.TextField()),
                ('color', models.TextField()),
                ('fecha_fabricacion', models.DateField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zona_DRS_APP.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('coste', models.FloatField()),
                ('mecanico', models.ManyToManyField(related_name='reparaciones', to='Zona_DRS_APP.mecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zona_DRS_APP.vehiculo')),
            ],
        ),
    ]
