# Generated by Django 5.1.2 on 2024-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zona_DRS_APP', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='apellido1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='apellido2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Coche', 'Coche'), ('Moto', 'Moto'), ('Camión', 'Camión')], max_length=10),
        ),
    ]
